-- Script was generated by Devart dbForge Studio for MySQL, Version 4.50.285.0
-- Script date 10/02/2015 0:31:23
-- Server version: 5.5.39
-- Client version: 4.1

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

-- 
-- Set default database
--
USE alumno;

--
-- Definition for table perfil
--
DROP TABLE IF EXISTS perfil;
CREATE TABLE perfil (
  id INT(11) NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(255) DEFAULT NULL,
  apellido VARCHAR(255) DEFAULT NULL,
  edad INT(11) DEFAULT NULL,
  estado CHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 5
AVG_ROW_LENGTH = 4096
CHARACTER SET utf8
COLLATE utf8_spanish_ci;

-- 
-- Dumping data for table perfil
--
INSERT INTO perfil VALUES 
  (1, 'alexis', 'morales samanez', 23, '1'),
  (2, 'jhon', 'castro blas', 22, '1'),
  (3, 'junior', 'falcon fernandez', 22, '1'),
  (4, 'victor', 'morales flores', 22, '1');

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;